name: test
on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout x509-mode
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install emacs
      uses: purcell/setup-emacs@1e197d195393d2568f9a239967e89104b2b63897 # v8.0
      with:
        version: 29.4
    - name: Run linting
      run: make lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
        - 27.2
        - 28.2
        - 29.4
        - 30.2
        - snapshot
    steps:
    - name: Install emacs
      uses: purcell/setup-emacs@1e197d195393d2568f9a239967e89104b2b63897 # v8.0
      with:
        version: ${{ matrix.emacs_version }}
    - name: Checkout x509-mode
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Build x509-mode
      run: make lisp
    - name: Test x509-mode
      run: make test
