name: test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
        - 27.2
        - 28.2
        - 29.4
        - snapshot
    steps:
    - name: Install emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Checkout x509-mode
      uses: actions/checkout@v3
      with:
        repository: jobbflykt/x509-mode
        path: x509-mode
    - name: Build x509-mode
      run: make -C x509-mode lisp
    - name: Test x509-mode
      run: make -C x509-mode test
